provider: cutting_shape

provider_kwargs:
  cutting_shape_path: "/home/muzhi/Datasets/Cutting-data/unit_aligned_mesh"

output: "di-datasets/cutting_shape"

sample_method: 1
sampler_var: 0.00015
sampler_count: 800000

write_pc: true

nproc: 4
