# Network parameters 
training_hyper_path: "di-checkpoints/train_cutting/hyper.json"
use_epoch: 500

# If input path ends with .ply, we take one file; if input path is a directory, we take all the files sequentially 
# input_path: "di-datasets/cutting_shape/pc/000001.ply"
input_path: "di-datasets/cutting_shape/pc"

output_path: "di-outputs/cutting_shape"
max_shape_num: 10

resolution: 256
max_samples_per_split: 400000
